# Add a zip built for new ES-version to existing release
name: Add release archive
on:
  workflow_dispatch:
    inputs:
      # TODO: detect this automatically from tag name
      releaseId:
        required: true
        type: string
        description: "Id of the release to update"
      releaseVersion:
        required: true
        type: string
        description: "Release version to checkout"
      elasticsearchVersion:
        required: true
        type: string
        description: "Version of target Elasticsearch"

# version: ${{ github.event.inputs.version }}
jobs:
  # TODO: duplication from build.yaml
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: v${{ github.event.inputs.releaseVersion }}
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          java-version: 8
      - uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3
      - uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: build -DbaseVersion=${{ github.event.inputs.releaseVersion }} -DelasticsearchVersion=${{ github.event.inputs.elasticsearchVersion }}
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ github.event.inputs.releaseId }}
          args: 'build/distributions/*.zip'
